export type CalendarEventType =
  | 'contract_expiry' | 'contract_renewal'
  | 'maintenance_scheduled' | 'maintenance_corrective'
  | 'assembly_ago' | 'assembly_age'
  | 'invoice_due' | 'inspection'
  | 'ticket_critical' | 'insurance_renewal'
  | 'budget_review' | 'amenity_booking' | 'custom';

export type CalendarEventStatus = 'scheduled' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled';

export interface Participant {
  name: string;
  email: string;
  type: 'contact' | 'external';
}

export interface CalendarEvent {
  id: string;
  condominium_id?: string;
  event_type: CalendarEventType;
  title: string;
  description?: string;
  start_at: string;
  end_at?: string;
  is_all_day: boolean;
  location?: string;
  status: CalendarEventStatus;
  source: 'system' | 'manual' | 'google' | 'microsoft' | 'apple_ics';
  created_by?: string;
  building_name?: string;
  participants?: Participant[];
  autoGenerated?: boolean;
  sourceModule?: string;
  reminder?: string;
  recurrence?: string;
  priority?: 'normal' | 'high' | 'urgent';
}

export const EVENT_TYPE_CONFIG: Record<CalendarEventType, {
  label: string;
  labelKey: string;
  emoji: string;
  pillBg: string;
  pillText: string;
  allowedRoles: string[];
}> = {
  contract_expiry:        { label: 'Vencimento de Contrato',          labelKey: 'calendar.type.contractExpiry',        emoji: '📋', pillBg: 'bg-amber-100',   pillText: 'text-amber-800',  allowedRoles: ['super_admin','gestor_fundo','building_manager'] },
  contract_renewal:       { label: 'Renovação de Contrato',           labelKey: 'calendar.type.contractRenewal',       emoji: '📝', pillBg: 'bg-cyan-100',    pillText: 'text-cyan-800',   allowedRoles: ['super_admin','gestor_fundo','building_manager'] },
  maintenance_scheduled:  { label: 'Manutenção Preventiva',           labelKey: 'calendar.type.maintenanceScheduled',  emoji: '🔧', pillBg: 'bg-blue-100',    pillText: 'text-blue-800',   allowedRoles: ['super_admin','building_manager','owner'] },
  maintenance_corrective: { label: 'Manutenção Corretiva',            labelKey: 'calendar.type.maintenanceCorrective', emoji: '⚠️', pillBg: 'bg-orange-100',  pillText: 'text-orange-800', allowedRoles: ['super_admin','building_manager','owner'] },
  assembly_ago:           { label: 'Assembleia Geral Ordinária',      labelKey: 'calendar.type.assemblyAgo',           emoji: '🏛', pillBg: 'bg-purple-100',  pillText: 'text-purple-800', allowedRoles: ['super_admin','building_manager','owner','tenant_admin','gestor_fundo'] },
  assembly_age:           { label: 'Assembleia Geral Extraordinária', labelKey: 'calendar.type.assemblyAge',           emoji: '🏛', pillBg: 'bg-purple-200',  pillText: 'text-purple-900', allowedRoles: ['super_admin','building_manager','owner','tenant_admin','gestor_fundo'] },
  invoice_due:            { label: 'Vencimento de Boleto',            labelKey: 'calendar.type.invoiceDue',            emoji: '💰', pillBg: 'bg-red-100',     pillText: 'text-red-800',    allowedRoles: ['super_admin','gestor_fundo','owner','tenant_admin'] },
  inspection:             { label: 'Vistoria',                        labelKey: 'calendar.type.inspection',            emoji: '🔍', pillBg: 'bg-teal-100',    pillText: 'text-teal-800',   allowedRoles: ['super_admin','building_manager','owner','tenant_admin'] },
  ticket_critical:        { label: 'Chamado Crítico',                 labelKey: 'calendar.type.ticketCritical',        emoji: '⚡', pillBg: 'bg-rose-100',    pillText: 'text-rose-800',   allowedRoles: ['super_admin','building_manager','owner'] },
  insurance_renewal:      { label: 'Renovação de Seguro',             labelKey: 'calendar.type.insuranceRenewal',      emoji: '🛡', pillBg: 'bg-green-100',   pillText: 'text-green-800',  allowedRoles: ['super_admin','gestor_fundo','building_manager'] },
  budget_review:          { label: 'Revisão de Orçamento',            labelKey: 'calendar.type.budgetReview',          emoji: '📊', pillBg: 'bg-slate-100',   pillText: 'text-slate-700',  allowedRoles: ['super_admin','gestor_fundo','owner'] },
  amenity_booking:        { label: 'Reserva de Área Comum',           labelKey: 'calendar.type.amenityBooking',        emoji: '🏊', pillBg: 'bg-indigo-100',  pillText: 'text-indigo-800', allowedRoles: ['super_admin','building_manager','owner','tenant_admin','tenant_employee'] },
  custom:                 { label: 'Evento Personalizado',            labelKey: 'calendar.type.custom',                emoji: '⭐', pillBg: 'bg-pink-100',    pillText: 'text-pink-800',   allowedRoles: ['super_admin','owner'] },
};

// ICS utilities
export const formatICSDate = (date: string, time?: string): string => {
  const d = date.replace(/-/g, '');
  if (!time) return d;
  const t = time.replace(/:/g, '');
  return `${d}T${t}00`;
};

export const generateICS = (events: CalendarEvent[]): string => {
  const vevents = events.map(ev => {
    const startDate = ev.start_at.split('T')[0];
    const startTime = ev.start_at.includes('T') ? ev.start_at.split('T')[1]?.slice(0, 5) : undefined;
    const endDate = ev.end_at?.split('T')[0] || startDate;
    const endTime = ev.end_at?.includes('T') ? ev.end_at.split('T')[1]?.slice(0, 5) : startTime ? (parseInt(startTime.split(':')[0]) + 1).toString().padStart(2, '0') + ':' + startTime.split(':')[1] : undefined;
    return [
      'BEGIN:VEVENT',
      `DTSTART:${formatICSDate(startDate, startTime)}`,
      `DTEND:${formatICSDate(endDate, endTime)}`,
      `SUMMARY:${ev.title}`,
      `DESCRIPTION:${(ev.description ?? '').replace(/\n/g, '\\n')}`,
      `LOCATION:${ev.location ?? ''}`,
      `STATUS:CONFIRMED`,
      `UID:${ev.id}@luxcondo.app`,
      'END:VEVENT',
    ].join('\r\n');
  }).join('\r\n');

  return [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//LUXCondo//Safra Gestão//PT',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    vevents,
    'END:VCALENDAR',
  ].join('\r\n');
};

export const downloadICS = (events: CalendarEvent[], filename: string) => {
  const blob = new Blob([generateICS(events)], { type: 'text/calendar;charset=utf-8' });
  const a = Object.assign(document.createElement('a'), { href: URL.createObjectURL(blob), download: filename });
  a.click();
  URL.revokeObjectURL(a.href);
};

export const exportToGoogle = (ev: CalendarEvent) => {
  const startDate = ev.start_at.split('T')[0];
  const startTime = ev.start_at.includes('T') ? ev.start_at.split('T')[1]?.slice(0, 5) : '09:00';
  const endDate = ev.end_at?.split('T')[0] || startDate;
  const endTime = ev.end_at?.includes('T') ? ev.end_at.split('T')[1]?.slice(0, 5) : '10:00';
  const url = new URL('https://calendar.google.com/calendar/render');
  url.searchParams.set('action', 'TEMPLATE');
  url.searchParams.set('text', ev.title);
  url.searchParams.set('dates', `${formatICSDate(startDate, startTime)}/${formatICSDate(endDate, endTime)}`);
  url.searchParams.set('details', ev.description ?? '');
  url.searchParams.set('location', ev.location ?? '');
  window.open(url.toString(), '_blank');
};

export const exportToOutlook = (ev: CalendarEvent) => {
  const startDate = ev.start_at.split('T')[0];
  const startTime = ev.start_at.includes('T') ? ev.start_at.split('T')[1]?.slice(0, 5) : '09:00';
  const endDate = ev.end_at?.split('T')[0] || startDate;
  const endTime = ev.end_at?.includes('T') ? ev.end_at.split('T')[1]?.slice(0, 5) : '10:00';
  const url = new URL('https://outlook.live.com/calendar/0/deeplink/compose');
  url.searchParams.set('subject', ev.title);
  url.searchParams.set('startdt', `${startDate}T${startTime}:00`);
  url.searchParams.set('enddt', `${endDate}T${endTime}:00`);
  url.searchParams.set('body', ev.description ?? '');
  url.searchParams.set('location', ev.location ?? '');
  window.open(url.toString(), '_blank');
};

// Mock calendar events
export const mockCalendarEvents: CalendarEvent[] = [
  { id: 'ce1', event_type: 'contract_expiry', title: 'Vencimento — Caxias Park', start_at: '2025-12-01', is_all_day: true, status: 'scheduled', source: 'system', building_name: 'Caxias Park' },
  { id: 'ce2', event_type: 'contract_expiry', title: 'Vencimento — Extrema BP I', start_at: '2026-02-01', is_all_day: true, status: 'scheduled', source: 'system', building_name: 'Extrema BP I' },
  { id: 'ce3', event_type: 'maintenance_scheduled', title: 'Manutenção Docas — Caxias Park', description: 'Manutenção preventiva trimestral das docas.', start_at: '2026-04-08T09:00:00', end_at: '2026-04-08T17:00:00', is_all_day: false, status: 'confirmed', source: 'system', location: 'Docas', building_name: 'Caxias Park', autoGenerated: true, sourceModule: 'manutenção' },
  { id: 'ce4', event_type: 'assembly_ago', title: 'AGO — VILG11', description: 'Assembleia Geral Ordinária para aprovação de contas 2025.', start_at: '2026-04-15T19:00:00', end_at: '2026-04-15T21:00:00', is_all_day: false, status: 'scheduled', source: 'system', location: 'Sala de Reuniões', building_name: 'Portfolio Proprietário', participants: [{ name: 'Roberto Mendes', email: 'roberto@proprietario.com.br', type: 'contact' }] },
  { id: 'ce5', event_type: 'invoice_due', title: 'Boleto — Caxias Park · R$ 42.800', start_at: '2026-04-10', is_all_day: true, status: 'scheduled', source: 'system', building_name: 'Caxias Park', autoGenerated: true, sourceModule: 'financeiro' },
  { id: 'ce6', event_type: 'inspection', title: 'Vistoria AVCB — CD Cariacica', description: 'Vistoria do Corpo de Bombeiros para renovação do AVCB.', start_at: '2026-04-22T10:00:00', end_at: '2026-04-22T12:00:00', is_all_day: false, status: 'scheduled', source: 'system', location: 'Galpão principal', building_name: 'CD Cariacica', participants: [{ name: 'Tatiana Caracciolo', email: 'tatiana@administradora.com.br', type: 'contact' }] },
  { id: 'ce7', event_type: 'contract_expiry', title: 'Vencimento — Caxias Park', start_at: '2026-06-01', is_all_day: true, status: 'scheduled', source: 'system', building_name: 'Caxias Park' },
  { id: 'ce8', event_type: 'amenity_booking', title: 'Reserva Sala — Ambev S.A.', start_at: '2026-04-12T14:00:00', end_at: '2026-04-12T16:00:00', is_all_day: false, status: 'confirmed', source: 'manual', location: 'Sala de Reuniões', building_name: 'Caxias Park' },
  { id: 'ce9', event_type: 'budget_review', title: 'Revisão Orçamento Q2 — Proprietário', description: 'Revisão e aprovação do orçamento Q2 2026.', start_at: '2026-04-28T10:00:00', end_at: '2026-04-28T12:00:00', is_all_day: false, status: 'scheduled', source: 'manual', building_name: 'Portfolio Proprietário', location: 'Sede Safra', participants: [{ name: 'Daniel Amaro', email: 'daniel@administradora.com.br', type: 'contact' }] },
  { id: 'ce10', event_type: 'insurance_renewal', title: 'Renovação Seguro — Alianza Park', start_at: '2026-04-30', is_all_day: true, status: 'scheduled', source: 'system', building_name: 'Alianza Park', autoGenerated: true, sourceModule: 'documentos' },
  { id: 'ce11', event_type: 'maintenance_corrective', title: 'Reparo Ar-Condicionado — Galpão A2', start_at: '2026-04-05T08:00:00', end_at: '2026-04-05T12:00:00', is_all_day: false, status: 'in_progress', source: 'system', location: 'Galpão A2', building_name: 'Caxias Park' },
  { id: 'ce12', event_type: 'custom', title: 'Treinamento Brigada de Incêndio', description: 'Treinamento anual obrigatório para a brigada de incêndio.', start_at: '2026-04-18T14:00:00', end_at: '2026-04-18T17:00:00', is_all_day: false, status: 'scheduled', source: 'manual', location: 'Área Externa', building_name: 'Caxias Park' },
  // VILG11 asset events
  { id: 'ce13', event_type: 'inspection', title: 'Vistoria AVCB — CD Cariacica', description: 'Vistoria urgente do AVCB. Renovação anual obrigatória.', start_at: '2026-04-15T09:00:00', end_at: '2026-04-15T12:00:00', is_all_day: false, status: 'scheduled', source: 'system', location: 'CD Cariacica', building_name: 'CD Cariacica', autoGenerated: true, sourceModule: 'documentos', participants: [{ name: 'Tatiana Caracciolo', email: 'tatiana@administradora.com.br', type: 'contact' }] },
  { id: 'ce14', event_type: 'contract_renewal', title: 'Reunião renovação — Galpão A1 Caxias Park', description: 'Reunião com locatário para renovação de contrato.', start_at: '2026-04-30T14:00:00', end_at: '2026-04-30T15:30:00', is_all_day: false, status: 'scheduled', source: 'manual', building_name: 'Caxias Park' },
  { id: 'ce15', event_type: 'contract_expiry', title: 'Reunião DHL — renovação', description: 'Discussão de renovação contratual do Galpão C2.', start_at: '2026-05-10T10:00:00', end_at: '2026-05-10T11:30:00', is_all_day: false, status: 'scheduled', source: 'manual', building_name: 'Caxias Park' },
  { id: 'ce16', event_type: 'maintenance_scheduled', title: 'Inspeção predial anual — Caxias Park', description: 'Inspeção predial anual completa.', start_at: '2026-05-20T08:00:00', end_at: '2026-05-20T17:00:00', is_all_day: false, status: 'scheduled', source: 'system', building_name: 'Caxias Park' },
  { id: 'ce17', event_type: 'inspection', title: 'Vencimento PMOC — CD Cariacica', start_at: '2026-06-01', is_all_day: true, status: 'scheduled', source: 'system', building_name: 'CD Cariacica' },
  // Additional rich events
  { id: 'ce18', event_type: 'invoice_due', title: 'IPTU Parcela 4/12 — CD Cariacica', description: 'Vencimento da 4ª parcela do IPTU 2026. Valor: R$ 4.200', start_at: '2026-04-09', is_all_day: true, status: 'scheduled', source: 'system', building_name: 'CD Cariacica', autoGenerated: true, sourceModule: 'financeiro', priority: 'normal' },
  { id: 'ce19', event_type: 'invoice_due', title: 'IPTU Parcela 4/12 — Airport Town GRU III', description: 'Vencimento da 4ª parcela do IPTU 2026. Valor: R$ 3.800', start_at: '2026-04-09', is_all_day: true, status: 'scheduled', source: 'system', building_name: 'Airport Town GRU III', autoGenerated: true, sourceModule: 'financeiro', priority: 'normal' },
  { id: 'ce20', event_type: 'contract_expiry', title: 'Garantia DHL — Vencendo em 22 dias', description: 'ALERTA: Seguro fiança DHL vence em 30/04/2026. Providenciar renovação.', start_at: '2026-04-30T08:00:00', end_at: '2026-04-30T08:30:00', is_all_day: false, status: 'scheduled', source: 'system', building_name: 'Caxias Park', autoGenerated: true, sourceModule: 'contratos', priority: 'urgent', participants: [{ name: 'Tatiana Caracciolo', email: 'tatiana@administradora.com.br', type: 'contact' }] },
  { id: 'ce21', event_type: 'contract_renewal', title: 'Reajuste IGP-M — Magazine Luiza Galpão A1', description: 'Data limite para aplicação do reajuste IGP-M 4,82%.', start_at: '2026-04-10T09:00:00', end_at: '2026-04-10T09:30:00', is_all_day: false, status: 'scheduled', source: 'system', building_name: 'Caxias Park', autoGenerated: true, sourceModule: 'contratos', priority: 'urgent' },
  { id: 'ce22', event_type: 'maintenance_scheduled', title: 'PMOC — Manutenção Preventiva HVAC', description: 'Manutenção preventiva mensal do sistema HVAC — ClimaTech Solutions.', start_at: '2026-05-06T08:00:00', end_at: '2026-05-06T12:00:00', is_all_day: false, status: 'scheduled', source: 'system', location: 'Área administrativa CD Cariacica', building_name: 'CD Cariacica', participants: [{ name: 'ClimaTech Solutions', email: 'contato@climatech.com.br', type: 'contact' }] },
  { id: 'ce23', event_type: 'assembly_ago', title: 'Assembleia de Cotistas Q2', description: 'Assembleia ordinária de cotistas. Pauta: resultados Q1, distribuição de rendimentos.', start_at: '2026-05-15T10:00:00', end_at: '2026-05-15T12:00:00', is_all_day: false, status: 'scheduled', source: 'manual', location: 'Sede Safra — Sala de Conselho', building_name: 'Portfolio Proprietário', participants: [{ name: 'Roberto Mendes', email: 'roberto@proprietario.com.br', type: 'contact' }, { name: 'Daniel Amaro', email: 'daniel@administradora.com.br', type: 'contact' }] },
  { id: 'ce24', event_type: 'invoice_due', title: 'IPTU Parcela 5/12 — CD Cariacica', description: 'Vencimento da 5ª parcela IPTU 2026. R$ 4.200', start_at: '2026-05-09', is_all_day: true, status: 'scheduled', source: 'system', building_name: 'CD Cariacica', autoGenerated: true, sourceModule: 'financeiro' },
  { id: 'ce25', event_type: 'budget_review', title: 'Entrega Relatório ESG Q1/2026', description: 'Prazo de entrega do relatório ESG Q1 2026 para a CVM.', start_at: '2026-05-31T18:00:00', end_at: '2026-05-31T18:30:00', is_all_day: false, status: 'scheduled', source: 'system', building_name: 'Portfolio Proprietário', autoGenerated: true, sourceModule: 'ESG' },
];
